### PR TITLE
Added Google Authorisation and edited the NavBar to show user name an…

### LINKED ISSUE #7: add login/ logout using react-oauth/google library
read more about the library
https://www.npmjs.com/package/@react-oauth/google

### PR DESCRIPTION
**Pull request by ArinCodes**
Closes : #7 

1. I Have added the Google Authorisation Login / SignOut  Functionality in the Navbar
2.  I have also  Edited the Navbar to show the User name (The one who is Signed in ) and Gmail account picture (It Looks Cool😉)
3.  This Functionality  will only work on Development Environment and Not the Production Environment as you guys have not put it out on production yet . Once It's Out for Production  You guys can contact me and  I will update the Authorised Javascript Origins and update the URL's over there so that it can work both on the development and Production environment (Just email me❤️)

### CODE REVIEW

**Comment by ArinCodes** [comment]
Navbar

**Review by Aadarsh805 — COMMENTED** [review]
Lgtm

**Comment by Aadarsh805** [comment]
@ArinCodes great job bro

**Comment by Aadarsh805** [comment]
what I'm gonna do is move logout button to user-profile modal

**Comment by ArinCodes** [comment]
Keep in mind to remind me when you guys push the site into production. I"ll update the URLs in my google console

**Comment by Aadarsh805** [comment]
> Keep in mind to remind me when you guys push the site into production. I"ll update the URLs in my google console

yeah sure

**Comment by ArinCodes** [comment]
Hey !!can you add hacktoberfest-accepted label in the PR so it can get accepted in Hacktoberfest

**Comment by Aadarsh805** [comment]
@ArinCodes you there bro, we deployed the site for testing purposes

**Pull request merged**
