### PR TITLE
Added the design figma file

### PR DESCRIPTION
**Pull request by Rohan-Hazari**
Fixes issue #43

### CODE REVIEW

**Comment by Rohan-Hazari** [comment]
Also moved the album page design in album folder

**Review by Aman-Mandal — APPROVED** [review]
Thankyouu Rohan!! highly appreciated :)

**Comment by Rohan-Hazari** [comment]
> Thankyouu Rohan!! highly appreciated :)

Thank you 
Also Do let me know your Genuine opinion on my designing Skills

**Comment by Aman-Mandal** [comment]
> > Thankyouu Rohan!! highly appreciated :)
> 
> Thank you 
> Also Do let me know your Genuine opinion on my designing Skills 

Will text you tomorrow on this matter🤜🤛

**Pull request merged**
