### PR TITLE
Gurudatt puranik

### PR DESCRIPTION
**Pull request by gurudattpuranik25**
- Added key prop in TopArtists component
- Designed footer section
- Added podcasts under /Podcast

### CODE REVIEW

**Comment by Aman-Mandal** [comment]
Thanks for contributing 😃

Will review it and then merge it..or vice versa

**Review by alicalimli — APPROVED** [review]
Nice work!

**Comment by gurudattpuranik25** [comment]
Thank you team... would consider contributing to the functionalities as well.🙌🙌

**Comment by gurudattpuranik25** [comment]
> Nice work!

Thank you Ali ☺

**Pull request merged**
