### PR TITLE
bug: navbar icon visibility

### LINKED ISSUE #134: [BUG] The Icons on the Navbar got transparent
All the icons on the Navbar got transparent or black 
image

Make it look like the Original UI

### PR DESCRIPTION
**Pull request by Anish-Sarawgi**
### Description 
Navbar icons visibility fixed.

### Linked Issues
Fixes #134 

### Screenshot
image

❤️Thank you!

### CODE REVIEW

**Review by Aadarsh805 — COMMENTED** [review]
wait what did you change yarn.lock ?

**Comment by Anish-Sarawgi** [comment]
> wait what did you change yarn.lock ?

Yes. The icons are visible now. You can see the screenshot in the description.

**Comment by Aman-Mandal** [comment]
> > wait what did you change yarn.lock ?
> 
> Yes. The icons are visible now. You can see the screenshot in the description.

But how did you know..that you have to make changes in yarn.lock?

**Comment by Aadarsh805** [comment]
> > > wait what did you change yarn.lock ?
> > 
> > 
> > Yes. The icons are visible now. You can see the screenshot in the description.
> 
> But how did you know..that you have to make changes in yarn.lock?

same question

**Pull request merged**
