### PR TITLE
Work on player (play/pause functionality)

### PR DESCRIPTION
**Pull request by mastermanav09**

### CODE REVIEW

**Comment by mastermanav09** [comment]
Just a reminder, Please correct the spelling of hacktoberfest in the topics. None of my PRs are being considered for hacktoberfest.😅

**Comment by Aman-Mandal** [comment]
Can I merge first and then do a review?

**Comment by Aman-Mandal** [comment]
Looks very nice Manav!! 😀
Btw, can we fix the height of the player so that it won't increase when we populate data in the genres and charts section.

Do lemme know what do you think about this!!

And I think you are way too experienced !! Thanks for contributing :)

**Review by Aman-Mandal — COMMENTED** [review]
Looks very nice Manav!! 😀
Btw, can we fix the height of the player so that it won't increase when we populate data in the genres and charts section.

Do lemme know what do you think about this!!

And I think you are way too experienced !! Thanks for contributing :)

**Comment by Aadarsh805** [comment]
#20

**Pull request merged**
