### PR TITLE
Work on responsiveness of homepage

### PR DESCRIPTION
**Pull request by mastermanav09**
Fix the all-artist overflow issue and made sidebar more responsive to tablet.
Re-work on navbar.

### CODE REVIEW

**Review by Aman-Mandal — APPROVED** [review]
Wow!! I personally like that Cross component 😃

Highly appreciated..Thanks Ser

**Comment by mastermanav09** [comment]
Hey! Thank you for giving us the opportunity for working on your project!😄 I just wanted to point out that the spelling of the hacktoberfest is wrong in the topics section. (missed out k).

**Comment by Aman-Mandal** [comment]
> Hey! Thank you for giving us the opportunity for working on your project!😄 I just wanted to point out that the spelling of the hacktoberfest is wrong in the topics section. (missed out k). 

Ohh Damnn...thanks for letting me know!! Will change that🤞

**Comment by Aadarsh805** [comment]
@mastermanav09 the navbar and explore component should have a 80 left margin when sidebar is closed on desktop 
Screenshot from 2022-10-06 00-48-18

**Comment by mastermanav09** [comment]
Like when sidebar is opened, the navbar and the explore component should be shifted to right by margin 80 ?

**Comment by Aadarsh805** [comment]
> Like when sidebar is opened, the navbar and the explore component should be shifted to right by margin 80 ?

yeah it should not go behind sidebar when on desktop, I'm working on it don't worry

**Comment by mastermanav09** [comment]
Okay, thanks

**Pull request merged**
