### PR TITLE
SearchBar is working now

### PR DESCRIPTION
**Pull request by nidhi333-9**

### CODE REVIEW

**Comment by nidhi333-9** [comment]
The search bar is working now. It's fetching the data from the data>trending songs

**Review by Aadarsh805 — COMMENTED** [review]
let me merge and see

**Review by Aadarsh805 — COMMENTED** [review]
yes this is great

**Comment by Aadarsh805** [comment]
@nidhi333-9 great job Nidhi

**Comment by Aadarsh805** [comment]
#8

**Comment by nidhi333-9** [comment]
@Aadarsh805 Thanks :)

**Pull request merged**
