### PR TITLE
Solution for issue regarding making trending new hits scrollable and dynamic (issue #26)

### PR DESCRIPTION
**Pull request by PrajwalDhule**
#26  pull request is for solution regarding the issue of making the trending new hits section scrollable with pagination effect and adding dummy data and making the section dynamic. I used useState hook to change index when moving up and down and useEffect hook to add and remove appropriate tailwind classes from elements when the index is changed. I have put the songs data in an array of objects in a js file in data folder.

### CODE REVIEW

**Review by Aman-Mandal — APPROVED** [review]
Look good Prajwal..Let me first merge it and then I will ask for changes if needed!!

Thanks :)

**Comment by PrajwalDhule** [comment]
Sure, thanks!

**Comment by Aman-Mandal** [comment]
> Look good Prajwal..Let me first merge it and then I will ask for changes if needed!!
> 
> Thanks :)

It's fine from my side but I would like @Aadarsh805 to review it too

**Review by Aadarsh805 — COMMENTED** [review]
lgtm

**Comment by Aadarsh805** [comment]
good work @PrajwalDhule

**Comment by Aadarsh805** [comment]
#26

**Pull request merged**
