### PR TITLE
Navbar 1

### PR DESCRIPTION
**Pull request by Aadarsh805**

### CODE REVIEW

**Comment by Aadarsh805** [comment]
i hope nothing breaks

**Comment by Aman-Mandal** [comment]
We already had a Navbar na? so why a new one..just asking?

**Comment by Aadarsh805** [comment]
> We already had a Navbar na? so why a new one..just asking?

Bro mb I did not pull or see the merged prs before started working

**Comment by Aman-Mandal** [comment]
> > We already had a Navbar na? so why a new one..just asking?
> 
> Bro mb I did not pull or see the merged prs before started working

Ohhh...no issues then!!

**Pull request merged**
