### PR TITLE
Top charts component added

### PR DESCRIPTION
**Pull request by hamzailyas237**
I have added the Top charts component, Please check it out and merge. If something is wrong let me know I will do it again.

### CODE REVIEW

**Review by Aman-Mandal — APPROVED** [review]
Looks good ...will ask some changes after merging

**Comment by hamzailyas237** [comment]
@Aman-Mandal Thank you.

**Comment by Aman-Mandal** [comment]
@hamzailyas237 It's not what we want Hamza!!

As you can see in the below image, we want top charts to be like that..I hope you will do the needful changes

image

**Comment by Aman-Mandal** [comment]
> @hamzailyas237 It's not what we want Hamza!!
> 
> As you can see in the below image, we want top charts to be like that..I hope you will do the needful changes
> 
> image

Make a component with,
1. serial number
2. Artist image
3. Artist name
4. song name
5. length of song
6. play button and an add to playlist(+) button

**Comment by hamzailyas237** [comment]
okay, i am doing it.

**Pull request merged**
