### PR TITLE
Fix : Fix the height of whole application [fixes #39]

### LINKED ISSUE #39: [Fix] Fix the height of whole application
Right now as you can see the height of the application keeps on increasing as we add more data, but it should be fixed!! 

image

### PR DESCRIPTION
**Pull request by najeebkp**
### Fix the height of whole application [fixes #39]

### CODE REVIEW

**Review by Aadarsh805 — COMMENTED** [review]
let me merge and see the changes

**Comment by Aadarsh805** [comment]
it's still scrolling a little, reducing the number of those genre and top charts didn't do much because those are fixes sizes so after reducing the number of genre of top charts makes extra space only and not change the height, what we have to do is decrease padding and gap and make things a little smaller and that'll go away

**Comment by Aadarsh805** [comment]
top charts is gonna be in columns so its gonna scroll more later

**Comment by najeebkp** [comment]
see, if you don't limit the number of Genre, then the list will go down and down. it will not help to keep the height fixed.
and there is a see all button also. that's why i fixed the Genre list. the same applicable to top charts. 
if you still want to fit in a single screen, then the design will be affected. we need to reduce images sizes and spaces.

**Comment by Aadarsh805** [comment]
yeah makes sense, we'll look into it again after the top charts section is done

**Comment by Aman-Mandal** [comment]
> see, if you don't limit the number of Genre, then the list will go down and down. it will not help to keep the height fixed.
> and there is a see all button also. that's why i fixed the Genre list. the same applicable to top charts. 
> if you still want to fit in a single screen, then the design will be affected. we need to reduce images sizes and spaces. 

We can fix the genre section and can make it scrollable from inside..what do u say? Just an opinion of mine

**Comment by Aadarsh805** [comment]
> > see, if you don't limit the number of Genre, then the list will go down and down. it will not help to keep the height fixed.
> > and there is a see all button also. that's why i fixed the Genre list. the same applicable to top charts.
> > if you still want to fit in a single screen, then the design will be affected. we need to reduce images sizes and spaces.
> 
> We can fix the genre section and can make it scrollable from inside..what do u say? Just an opinion of mine

yeah ig that would be best because top-charts component is definitely gonna take much more vertical space so we can make both scrollable

**Comment by najeebkp** [comment]
i dont think it will help the cause. then why do we have a "see all" button ?

**Comment by Aadarsh805** [comment]
"see all" is for their separate pages, where there'll be much more genres and separate listings of songs of those genres

**Comment by najeebkp** [comment]
> "see all" is for their separate pages, where there'll be much more genres and separate listings of songs of those genres

That's what i'm saying. at the home page, why we need to display every genre tags if there is a separate page for displaying it all.

**Comment by Aman-Mandal** [comment]
> > "see all" is for their separate pages, where there'll be much more genres and separate listings of songs of those genres
> 
> That's what i'm saying. at the home page, why we need to display every genre tags if there is a separate page for displaying it all.

Yeahh I think you're right!! We can just limit our genre on the homepage..

**Comment by Aadarsh805** [comment]
yeah we keep it like that, we'll look into it after we have top-charts component done

**Pull request merged**
